name: learn-github-actions
on: 
  push:
    branches:
      - main
jobs:
  build-ui:

    runs-on: self-hosted     

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}      
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}     
      working-directory: ./ui
    - run: npm install
    - run: npm run build --if-present


  build-server:
    needs: build-ui

    runs-on: self-hosted
      
    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1    
      with:
        node-version: ${{ matrix.node-version }}
      working-directory: ./ui
    - run: npm install

    